#----------------------------------------------------------------------
# This file was generated by c:\Python27\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

martus = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAACTlJ"
    "REFUWIXFlnd0lFUaxn/fzDczyZS0yaSTAkkgBSbBGGnBhQUFlEiOHhREBSXiAor0oqAgTVaW"
    "VUFRFhcrRQ2gVCkmSC/SQktiCimTHtInmXL3D5I9tOzB9ezZ55znfH/c893nue99772PJITg"
    "/wm5owFJkpRAT2Aw0A3wBZxAKXAR2C2EuPKHHQgh7iLQHdg0d96bjYD4/IuvRHi0WRQWFoup"
    "U2cIrU4vXhj7YhXwORB1rznul3cKK4AFU6ZMaxJCiIyMQ2Ltl2lix7kiER5tFkIIcSyvQqx6"
    "f41oxyOPDqsFXv5vDUjtPSBJkhpYaTbHT/7o03Vs3HGI7zesZsSYv1DXZOXEvu9I7N2X7vG9"
    "qau2cPjAHl55fS5BRlce7t/PDswXQiz/vTtwaw8sXLb8r5NbXP1Zu3EPpw9uIz6xHxoXF3TO"
    "myYNeh2W8kpUagOWiipWvrecHn2G8M22A/KR/duXSZLUJIT44PcYUAAkzd732NPPjJ41Z/YM"
    "8hzeNJpiiYiKJWbwGLKcfuQqgwDwjRlAkSaMYlUnnpu2lOjuPcnClxLhy+oP3yc8InLBuTrT"
    "okFLT01+4qeI5x48NzEp8Vt9wMiUM4oOK1C3rYd8eMXFWUIIxdmSarzcdHTz0ZG2u4AHvXx4"
    "yM2L3uYAJm57l7rKMmJCY9G6aKivtHAt8zTDUx8nLNBAvc3Gli2bjQsnrpkfnFCDj+VL0b1S"
    "Y/X2X1Q89Ejq4bxBo7aMm/d+RvrAI023GlAu31w+ILJrt3kag1Gxf89+aouzObLzG8osxfh6"
    "aGksuUbBtUyuXcmktbEajaOB8twLKK2V/Lz7B9xVDipKrrNnbwaV1dVk7NnOgCFPUtNklySc"
    "qsa6Gq9fB/eNy3woIHnJpMyQxcNWF7amK8sio803DQATistKkz79pQLZKxSFVwhGjSCu10Dq"
    "PaMwhsZQZDNQcv4gjzzzKjXaEDyDo4iOS8RDqyYmcQDFcjB2QwCRsQ8w6+WnOXz0hKhFL6lV"
    "MpIkAWC32zRH+yfEG5WTeqfnKStSEgMvt/dAlEapRKuRCfTxwikETmcrbiY/kCSabTZCfY03"
    "6yUpaLHZiQ7zo7DsBhq9B2XFhTicdtx1Ws5lF9E1MpySnAsHZ854c0NCYlKmUCitdocDAJUs"
    "U3M9q4c5KnTx0rVfRbdXYJqHf0hgXUk+rdUFKBvL+SntK3BY8dNK2KsLcBe1XDh7CltDDaFG"
    "V5rLcmmoKOL04b3kZ2cS7uuBraoAvaOa61lXWLrojbQ1ouSttI/ZXmzzyRqb+oq/pWhsgCRJ"
    "SJJEeXmZ92tTZ9e6zZ+cLgOtT49+hg82HUWllNCpXYmMOU5Ej97ofLsgnE4USiUAwVHxaINi"
    "kZUSepR06VqErFKhCzGjkiSQJEaNSSI1dRxAvRCiEsiZv2XM6UEpIxbt/X79MJVSRqtRcexs"
    "zjCiWK0ALH56FywNdqpaFBRU1uMfEo7GVc/VsgZqHDI2WQuAmykEg4c3TbhwsagKo8kPU2AX"
    "8qtbqLbJXCqt48SVSgArILV3+jsjo85Mevvv030CwvJsdjsOh4PKmmpdmaZzmAI4l1toIdjf"
    "yPA+kUSHBuCwtVJRlE1EkC9dA0zoXDQAdAsyENHJHb1aQVx4J/JzLqGQBHFdOhFsNBATEsip"
    "9B0ANcBtz2z2qqFXF3+S9jVtA95Gz9opL49uloHtEaFBrxWUlPts/DGD5lYnSBIZu9MY2SkC"
    "S4WNVrsTgOOHD2EKqQActDQ1cfKXAwSGdkNZeJGmZit6NcyZnloCnLy1Au3IV/Y8skqra2ps"
    "bNB6GLRVmz5cXKMQQmQKIbbJWh0R8Yng3RnfhGQCg0OoVPpQ4DQieUcAYAiJI8uqx4IJF7+u"
    "xPRIwBDRl7M1asLN/ejVMwogDcgFbHcaUMf+ySFJCKdTYNSpcoBGBUD4qJVnRo8YTkpCJ8qr"
    "66mqa0KncydUZ0OlUBDs7wWARlaiVavQu7piLb1GQkICCoWEOTyEpwYEM3HsswXANuCGEMJx"
    "p4Hxg7v5tVibdR6eXjfOZ+w6CjQqlp5JV76zekNS0oiX6D/wUWecoYooTRmSaGHv5o/xseaT"
    "fXQXAJeO/Ij7jStoKi+yZd0KKivKcG/Kp5dnFQF6Q3lBQd5K4FpbE96FuU9E9bG2tNI/MeH4"
    "C8kPnQdaJXncd8GLR/ZKV0hO1YKR8d8F+niNz8nO0h/KKWfBpFQef3Euv1U1s3/NVJLHzUTp"
    "3ZlOLs0YrIXEP5pMVx83XGW5HHgdSAeqhBCtd4q/tvnXzka17pjTbtO4NedNmPFC8j4hRDWJ"
    "9d8mTv/iVP0hi2EbEAo8BVzdnXFSXMi8IoamjBbrD+aI8GizyDhfKMqam8Wo0WOEEEKkbd0u"
    "gAvA80AwoOooeJwxjlw9eW2G+LXK/W9tOmohBFyerh8wdcPx5rOlmjcBz7aAEgC8HRbW+SrQ"
    "2KtXH1t4tFmER5uFu7unDWgAzgMLgQTACMgdiffb7DH21U8P2y63hn8GmAHtv1PYSf2gxAnr"
    "TpTl2/3G3zrQZiQCSAbGAOPb+DzwJBAPmAAt3ExW9+JnDxwYMu2fJ+qPVXpvBR4APG7T2Jhy"
    "Tv3ZeflordeDMwGXDkKq1EZlGxVt3w6FhRBMKB375JxNl4uyRLd1QBzgBijuCqXeg6fPyFV1"
    "XwNo/kjCbed67bOulsHrZy/bW3q5wZT0BhDZJn6XYRlgzlHrP7zNQ99qkJLjgBP3OkL3g+fK"
    "Z2n6PZbysCr3wqga0zGSb6TO0Fc4z3LzXmi+50/tTo4P3BU7do/hpb67YyNEanyH3Xwvevf8"
    "WbMk6udHLoW98p5LrymLZy3/aCjgAxj+08m4LZYDiD6vBidM3Bn20sfHm4sTVl3f1zO7Ztm7"
    "g2x7474WLo4GXNRq5n15QljypqrkP58y9HGvMq0IOxj0yRPGrrbLW62xpuqTH8ycWArUA04h"
    "xF3X8Z24zQCAJEmaQTti/G1dRmrdhk0QKROWOHb9sFf5m93VOf3xCE3Tb+eVY2JtHjSUyqWn"
    "tspDxM7arN2rc7n5AiqA1ntdwx2io9IA8oqzsbqdzgQ3l4Ua08Qrw4MW1r7onx33UfB6Sz+/"
    "0Knf+gA6QMV9nIj72oIOy9SeLG9/YkWbqPO+V3uvue/HwP8S/wJ0yWjHVSc/dQAAAABJRU5E"
    "rkJggg==")
getmartusData = martus.GetData
getmartusImage = martus.GetImage
getmartusBitmap = martus.GetBitmap
getmartusIcon = martus.GetIcon

